atlas_org_id               = "MY_ORG_ID"
atlas_project_name         = "Customer Portal - Prod"
cluster_instance_size_name = "M30"
atlas_region               = "US_WEST_2"
mongodb_version            = "8.0"
aws_iam_role_name          = "mongodb-atlas-lz-modules"
vpc_name                   = "mongodb-lz-modules-vpc"
aws_iam_role_arn_ec2       = "arn:aws:iam::123456789012:role/mongodb-atlas-lz-modules" #TODO: Create an ARN for ec2 instance
cluster_name               = "my-cluster"
