atlas_org_id               = "MY_ORG_ID"
atlas_project_name         = "Customer Portal - Prod"
environment                = "prod"
cluster_instance_size_name = "M30"
cloud_provider             = "AWS"
atlas_region               = "US_WEST_2"
mongodb_version            = "8.0"
